artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: C:\\Users\\VISHU\\Desktop\\End-to-EndProjects\\WineQualityPrediction\\artifacts\\data_ingestion\\winequality-red.csv

  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: C:\\Users\\VISHU\\Desktop\\End-to-EndProjects\\WineQualityPrediction\\artifacts\\data_ingestion\\winequality-red.csv